### ISSUE TITLE
Verify status of the Etherem transaction after deploying HTLC script

### ISSUE THREAD

**Issue by grandsmarquis** [liquality/chainify#154]
_I'm not 100% sure about this issue so I did not create a pull request. I'm just scratching the code base but it's maybe worth looking into a possible security flaw._

### What's the context

Imagine that I want to take part in an atomic swap (On the Ethereum side and being the one deciding the secret).
If I send my TX with insufficient gas it'll be reverted and I'll keep my ETH but the test to see if the transaction was correct only using the value and input inside of  `doesTransactionMatchSwapParams` will still pass. So I could trick the other person into believing everything is normal (if he does not verify the TX or balance on a block explorer).

### How to fix?

Also check for the transaction receipt status  line 97:

>  return transaction.input === data && transaction.value === value && transaction.status

In this file:

https://github.com/liquality/chainabstractionlayer/blob/fab06e57021f290c05fe1c4c5b533b4fb4bcf7d3/src/providers/ethereum/EthereumSwapProvider.js#L97

**Comment by monokh** [comment]
Hi @jdourlens 
Thanks for picking this up!
This has actually been partly addressed in the latest dev branch: https://github.com/liquality/chainabstractionlayer/commit/434adff6d51189784d676f3b01ad2f4cc689602e
Apologies that this wasn't present in the master branch. We should make an effort to push the latest changes to master more often. 

Having said that, I think you have identified the _correct_ place for this check to go. Additionally the `verify` call does not do this check in it's current form. So I think as you have pointed out, the check should be introduced in the `doesTransactionMatchParams` function instead of only within `findInitiateSwapTransaction`. This also would mean you can find the initiation even before it has succeeded/verified, allowing any consumer to know about it before it is fully confirmed (helpful for UIs for example)
